export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED"
export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING"

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED"
