export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED"
export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING"

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED"

export const GET_ONE_PRODUCTS_SUCCESS = "GET_ONE_PRODUCTS_SUCCESS"
export const GET_ONE_PRODUCT_FAILED = "GET_ONE_PRODUCT_FAILED"

export const POST_PRODUCTS_SUCCESS = "POST_PRODUCTS_SUCCESS"
export const POST_PRODUCT_FAILED = "POST_PRODUCT_FAILED"

export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS"
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED"